# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e7e9abcf239ad4ebefff6a15e35d8f5a39b53bad24d22f4e4f5bd3a70154f33667cae3e169e70f95ec41551e90ea527768cc3ab71e3180623106caba68a636c

test:
  secret_key_base: 9639acec5f1854586639730d9132b424ccfb084c1dc28676655650777b2a65def9eab9eaf66f38b7eb3190aa12d3e452920b7c7ff21229bec6e837871143cb64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
